In [ ]:
# 我们可以用创造性的方式组合不同的层，从而设计出适用于各种任务的神经网络计算拓扑架构；
# 例如，专用于处理图像、文本、序列数据和执行动态规划的层。

### 5.4.1 不带参数的层 

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

### 5.4.2 带参数的层 

In [6]:
# 我们可以使用内置函数来创建参数，这些函数提供一些基本的管理功能；
# 比如管理访问、初始化、共享、保存和加载模型参数。

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [8]:
# 实例化MyLinear类并访问其模型参数
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.7869,  0.9197, -2.2394],
        [ 1.6476, -1.1165, -0.6864],
        [-0.1229, -1.3095, -0.1413],
        [ 0.6140, -0.6986,  0.6692],
        [-0.1298,  0.0247, -1.0150]], requires_grad=True)

In [9]:
linear(torch.rand(2, 5))

tensor([[0.3215, 0.0000, 0.0000],
        [0.0000, 0.6638, 0.0000]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[5.7892],
        [0.4136]])